BUTTON_MAP = {
    "UP": "UP",
    "DOWN": "DOWN",
    "LEFT": "LEFT",
    "RIGHT": "RIGHT",
    "CROSS": "CROSS",
    "CIRCLE": "CIRCLE",
    "SQUARE": "SQUARE",
    "TRIANGLE": "TRIANGLE",
    "L1": "L1",
    "L2": "L2",
    "L3": "L3",
    "R1": "R1",
    "R2": "R2",
    "R3": "R3",
    "OPTIONS": "OPTIONS",
    "SHARE": "SHARE",
    "PS": "PS",
    "TOUCHPAD": "TOUCHPAD",
} 